### ISSUE TITLE
Notes Team Meeting 2021-10-06

### ISSUE THREAD

**Issue by murillol** [wpmarketingteam/Marcomms-Rolling#42]
Can I please get a reviewer for this week's meeting notes? Thanks!

**Comment by murillol** [comment]
> @murillol is this for 29th Sep or 6th Oct ?

October 6 2021 please!

**Comment by meherbala** [comment]
Hi, @murillol I have gone through the notes and made appropriate changes.

I am just puzzled about the Learn WP as it is at two different parts of the meeting.

--------------------------------------------------------------------------------------------

@abhansnuk please may I request you to just glance through the notes for 6th Oct 2021. Thanks
